title: Homelab Documentation
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-relative-links
  - jemoji
theme: minima
relative_links:
  enabled: true
  collections: true
baseurl: "/homelab"
header_pages:
  - index.md
  - ansible.md
  - proxmox.md
  - reverse-proxy.md
  - certificates.md
linkedin_username: frefol
github_username: t3knoid